name: Build and Package

on:
    workflow_dispatch:

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Configure CMake
              run: cmake -B build -DCMAKE_BUILD_TYPE=Release

            - name: Build
              run: cmake --build build --config Release

            - name: Package
              run: |
                  cmake --install build --config Release --prefix package
                  Compress-Archive -Path package/bin/* -DestinationPath build/InputBridge-Windows.zip

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-Windows
                  path: build/InputBridge-Windows.zip

    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Configure CMake
              run: cmake -B build -DCMAKE_BUILD_TYPE=Release

            - name: Build
              run: cmake --build build --config Release

            - name: Package
              run: |
                  cd build
                  cpack -C Release -G ZIP

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-macOS
                  path: build/*.zip

    build-ubuntu-appimage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libsamplerate0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev libxtst-dev

            - name: Configure and Build
              run: |
                  cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DSDL_SHARED=OFF -DSDL_STATIC=ON
                  DESTDIR=AppDir cmake --build build --target install

            - name: Create AppImage
              run: |
                  wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
                  chmod +x linuxdeploy-x86_64.AppImage
                  ./linuxdeploy-x86_64.AppImage --appdir build/AppDir --output appimage --icon-file build/org.inputbridge.InputBridge.svg --desktop-file build/org.inputbridge.InputBridge.desktop
                  mv InputBridge*.AppImage InputBridge-Ubuntu.AppImage

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-Ubuntu-AppImage
                  path: InputBridge-Ubuntu.AppImage

    build-fedora-appimage:
        runs-on: ubuntu-latest
        container:
            image: fedora:latest
        steps:
            - name: Install Git
              run: dnf install -y git

            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Dependencies
              run: |
                  dnf install -y gcc gcc-c++ cmake ninja-build pkg-config wget file tar \
                  alsa-lib-devel pulseaudio-libs-devel jack-audio-connection-kit-devel \
                  libsamplerate-devel libX11-devel libXext-devel libXrandr-devel \
                  libXcursor-devel libXfixes-devel libXi-devel libXScrnSaver-devel \
                  libxkbcommon-devel libdrm-devel mesa-libGL-devel mesa-libGLES-devel \
                  mesa-libEGL-devel mesa-libgbm-devel dbus-devel systemd-devel \
                  ibus-devel pipewire-devel wayland-devel libdecor-devel \
                  libXtst-devel openssl-devel zlib-devel fuse

            - name: Configure and Build
              run: |
                  cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DSDL_SHARED=OFF -DSDL_STATIC=ON
                  DESTDIR=AppDir cmake --build build --target install

            - name: Create AppImage
              run: |
                  wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
                  chmod +x linuxdeploy-x86_64.AppImage
                  ./linuxdeploy-x86_64.AppImage --appdir build/AppDir --output appimage --icon-file build/org.inputbridge.InputBridge.svg --desktop-file build/org.inputbridge.InputBridge.desktop
                  mv InputBridge*.AppImage InputBridge-Fedora.AppImage

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-Fedora-AppImage
                  path: InputBridge-Fedora.AppImage

    build-arch-appimage:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
        steps:
            - name: Install Git
              run: |
                  pacman -Sy --noconfirm git

            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Dependencies
              run: |
                  pacman -S --noconfirm base-devel cmake ninja pkg-config wget file tar \
                  alsa-lib libpulse jack2 libsamplerate libx11 libxext libxrandr \
                  libxcursor libxfixes libxi libxss libxkbcommon libdrm mesa \
                  libglvnd dbus systemd ibus pipewire wayland libdecor \
                  libxtst openssl zlib fuse2

            - name: Configure and Build
              run: |
                  cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DSDL_SHARED=OFF -DSDL_STATIC=ON
                  DESTDIR=AppDir cmake --build build --target install

            - name: Create AppImage
              run: |
                  wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
                  chmod +x linuxdeploy-x86_64.AppImage
                  ./linuxdeploy-x86_64.AppImage --appdir build/AppDir --output appimage --icon-file build/org.inputbridge.InputBridge.svg --desktop-file build/org.inputbridge.InputBridge.desktop
                  mv InputBridge*.AppImage InputBridge-Arch.AppImage

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-Arch-AppImage
                  path: InputBridge-Arch.AppImage

    build-ubuntu-flatpak:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Flatpak
              run: |
                  sudo apt-get update
                  sudo apt-get install -y flatpak flatpak-builder
                  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                  flatpak install --user -y org.freedesktop.Sdk//23.08 org.freedesktop.Platform//23.08

            - name: Build Flatpak
              run: |
                  flatpak-builder --user --disable-rofiles-fuse --force-clean build-dir org.inputbridge.InputBridge.yml
                  flatpak build-bundle repo InputBridge-Ubuntu.flatpak org.inputbridge.InputBridge

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-Ubuntu-Flatpak
                  path: InputBridge-Ubuntu.flatpak

    build-fedora-flatpak:
        runs-on: ubuntu-latest
        container:
            image: fedora:latest
        steps:
            - name: Install Git
              run: dnf install -y git

            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Flatpak
              run: |
                  dnf install -y flatpak flatpak-builder which ostree
                  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                  flatpak install --user -y org.freedesktop.Sdk//23.08 org.freedesktop.Platform//23.08

            - name: Build Flatpak
              run: |
                  flatpak-builder --user --disable-rofiles-fuse --force-clean build-dir org.inputbridge.InputBridge.yml
                  flatpak build-bundle repo InputBridge-Fedora.flatpak org.inputbridge.InputBridge

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-Fedora-Flatpak
                  path: InputBridge-Fedora.flatpak

    build-arch-flatpak:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
        steps:
            - name: Install Git
              run: |
                  pacman -Sy --noconfirm git

            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Flatpak
              run: |
                  pacman -S --noconfirm flatpak flatpak-builder which fuse2 ostree
                  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                  flatpak install --user -y org.freedesktop.Sdk//23.08 org.freedesktop.Platform//23.08

            - name: Build Flatpak
              run: |
                  flatpak-builder --user --disable-rofiles-fuse --force-clean build-dir org.inputbridge.InputBridge.yml
                  flatpak build-bundle repo InputBridge-Arch.flatpak org.inputbridge.InputBridge

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: InputBridge-Arch-Flatpak
                  path: InputBridge-Arch.flatpak
